stages:
  - .pre
  - build
  - test
  - deploy-staging
  - test-staging
  - deploy-production
  - test-production

variables:
  APP_BASE_URL: http://segun-20230819.s3-website-us-east-1.amazonaws.com
  APP_BASE_URL_STAGING: http://segun-20230819-staging.s3-website-us-east-1.amazonaws.com

build website:
  image: node:18-alpine
  stage: build
  script:
    - yarn install
    - yarn build
    - yarn test
    - yarn lint
  artifacts:
    paths:
      - build

test website:
  image: node:18-alpine
  stage: test
  script:
    - yarn global add serve
    - apk add curl
    - serve -s build & 
    - sleep 30
    - curl http://localhost:3000 | grep "React App"

deploy to staging:
  stage: deploy-staging
  image: 
    name: amazon/aws-cli:2.13.11
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - aws s3 sync build s3://$AWS_S3_BUCKET_STAGING --delete

test staging:
  stage: test-staging
  image: curlimages/curl
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - curl $APP_BASE_URL | grep "React App"

deploy to production:
  stage: deploy-production
  image: 
    name: amazon/aws-cli:2.13.11
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete

test production:
  stage: test-production
  image: curlimages/curl
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - curl $APP_BASE_URL-_STAGING | grep "React App"