stages:
  - .pre
  - build
  - test
  - deploy-staging
  - deploy-production

build website:
  image: node:18-alpine
  stage: build
  script:
    - yarn install
    - yarn build
    - yarn test
    - yarn lint
  artifacts:
    paths:
      - build

test website:
  image: node:18-alpine
  stage: test
  script:
    - yarn global add serve
    - apk add curl
    - serve -s build & 
    - sleep 30
    - curl http://localhost:3000 | grep "React App"

deploy to staging:
  stage: deploy-staging
  environment: staging
  image: 
    name: amazon/aws-cli:2.13.11
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - aws s3 sync build s3://$AWS_S3_BUCKET_STAGING --delete
    - curl $CI_ENVIRONMENT_URL | grep "React App"

deploy to production:
  stage: deploy-production
  environment: production
  image: 
    name: amazon/aws-cli:2.13.11
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete
    - curl $CI_ENVIRONMENT_URL | grep "React App"